### ISSUE TITLE
KeyError: 'DSC is not in the models registry'

### ISSUE THREAD

**Issue by wanxinjun** [hding2455/DSC#2]
KeyError: 'DSC is not in the models registry'

**Comment by wanxinjun** [comment]
Traceback (most recent call last):
  File "demo/image_demo.py", line 37, in <module>
    main()
  File "demo/image_demo.py", line 20, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "/home/wanxinjun/anaconda3/envs/dsc/lib/python3.7/site-packages/mmdet/apis/inference.py", line 39, in init_detector
    model = build_detector(config.model, test_cfg=config.get('test_cfg'))
  File "/home/wanxinjun/anaconda3/envs/dsc/lib/python3.7/site-packages/mmdet/models/builder.py", line 58, in build_detector
    cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/wanxinjun/anaconda3/envs/dsc/lib/python3.7/site-packages/mmcv/utils/registry.py", line 210, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/wanxinjun/anaconda3/envs/dsc/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 26, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/wanxinjun/anaconda3/envs/dsc/lib/python3.7/site-packages/mmcv/utils/registry.py", line 44, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'DSC is not in the models registry'

**Comment by hding2455** [comment]
That looks wired. Have you built the mmdet in this repo by running the python setup.py related command?

**Comment by jaideep11061982** [comment]
@hding2455  i too face same issue.
I copied .py files to new fold under configs  of my repo.
Any more step needed after copy ?

**Comment by jaideep11061982** [comment]
i had to copy dozens of file. it was reason of error

**Comment by hding2455** [comment]
I see. please use the whole repo instead of copy just one or two file

**Comment by jaideep11061982** [comment]
@hding2455 
I used this to work with latest mmdet version, yours may be too old to work .
```
!mkdir  ./mmdetection/configs/dsc
!cp  /dsc_r50_fpn_1x_coco.py  ./mmdetection/configs/dsc
!cp  /dsc_x101_32x4d_fpn_20e_coco.py  ./mmdetection/configs/dsc
!cp  /dsc.py ./mmdetection/mmdet/models/detectors/
!cp  /dsc_roi_head.py./mmdetection/mmdet/models/roi_heads/
!cp  /roi_heads_init.py ./mmdetection/mmdet/models/roi_heads/__init__.py

!cp ../dsc_mask_head.py ./mmdetection/mmdet/models/roi_heads/mask_heads/

!cp ./mask_head_init.py ./mmdetection/mmdet/models/roi_heads/mask_heads/__init__.py
!cp ./dsc_bbox_head.py ./mmdetection/mmdet/models/roi_heads/bbox_heads/
!dsc-configs/detectors_init.py                ./mmdetection/mmdet/models/detectors/__init__.py

!cp ./bbox_heads_init.py ./mmdetection/mmdet/models/roi_heads/bbox_heads/__init__.py
```

**Comment by hding2455** [comment]
Yeah, this is some work that happens more than one years ago. You can make a new virtual env and set up the corresponding packages for this and download the whole repo to work.
