### ISSUE TITLE
No of classes or semantic head

### ISSUE THREAD

**Issue by jaideep11061982** [hding2455/DSC#6]
How should i set classes for semantic head. 
For instance segmentation i have got three classes.  and in coco bbox head its 80

but semantic head its 183 ,dont know what to set there .please help
is it 2,(0,1)  or 3+1= bg+3 foreground

**Comment by hding2455** [comment]
Do you mean you are using your own dataset?

The semantic head is not for coco instance segmentation, it is actually dealing with the background segmentation ( You can see how semantic head works in the Hybrid Task Cascade paper, we adopted that from their work)
