### ISSUE TITLE
Urgent:DSCMaskHead Num classes issue

### ISSUE THREAD

**Issue by jaideep11061982** [hding2455/DSC#9]
I set all  num classes in heads as per my problem but still 
i get an error as
`
The `num_classes` (80) in DSCMaskHead of MMDataParallel does not matches the length of `CLASSES` 3) in CocoDataset`

for head in cfg.model.roi_head.bbox_head:
    head.num_classes = 3

cfg.model.roi_head.mask_head.num_classes=3

**Comment by jaideep11061982** [comment]
I think there is bug here ,you are not passing num classes so FCNMask   always defaults this to   80 

```
 mpn=[
            dict(
                type='DSCMaskHead',
                with_conv_res=False,
                num_convs=4,
                in_channels=256,
                conv_out_channels=256,
                class_agnostic=True,
                loss_mask=dict(
                    type='CrossEntropyLoss', use_mask=True, loss_weight=1.0)),
```

**Comment by hding2455** [comment]
I see, will you make a pull request to fix this or shall I just fix this myself?
